---
# Web Port Service (perhaps Nginx)
apiVersion: v1
kind: Service
metadata:
  name: raven-example-web
spec:
  # NodePort type allows to expose service outside the cluster
  type: NodePort
  selector:
    evalId: raven-example-pod
    tier: ta3
  ports:
    - name: http
      port: 80
      targetPort: 8080
    #- name: https
    #  port: 443
    #  targetPort: 443
---
apiVersion: v1
kind: Pod
metadata:
  name: raven-example-pod
  labels:
    evalId: raven-example-pod
spec:
  restartPolicy: Never
  containers:
  - name: raven-example
    image: tworavens/summer:latest
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      requests:
        memory: 512Mi
        cpu: 1
  imagePullSecrets:
  - name: regcred
  #volumes:
  #- name: input-data
  #  hostPath:
  #    path: /opt/datasets/seed_datasets_current/
  #    type: Directory
  #- name: output-data
  #  persistentVolumeClaim:
  #    claimName: output-pv-claim
